---

- name: Install docker-compose
  import_role:
    name: geerlingguy.docker
  become: yes

- name: Install pip and docker python packages
  import_role:
    name: geerlingguy.pip
  become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: "docker-compose=={{ docker_compose_version }}"

- name: Clone pathfinder-containers
  git:
    dest: "{{ pathfinder_dest }}"
    recursive: yes
    repo: "{{ pathfinder_repo }}"
  become: yes

- name: Configure .env for pathfinder-containers
  copy:
    src: "pathfinder-env"
    dest: "{{ pathfinder_dest }}/.env"
  become: yes

- name: Configure Docker network
  community.docker.docker_network:
    name: web

- name: Bring up docker-compose for pathfinder-containers
  community.docker.docker_compose:
    project_src: "{{ pathfinder_dest }}"
    state: present
